service: test

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-3

package:
  exclude:
  - '*'
  - '**'
  include:
  - bref.php
  - 'src/**'
  - 'vendor/**'
  # Below are Symfony-specific files and directories
  - composer.json # Symfony uses it to figure out the root directory
  - 'bin/**'
  - 'config/**'
  - 'var/cache/prod/**' # We want to deploy the production caches

functions:
  # By default we create one "main" function
  main:
    handler: handler.handle
    timeout: 20
    events:
    - http: 'ANY /'
    - http: 'ANY {proxy+}'
    # Symfony configuration using environment variables:
    environment:
      APP_ENV: 'prod'
      APP_DEBUG: '0'
