service: test

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-3

package:
  exclude:
    - '*'
    - '**'
  include:
    - bref.php
    - 'src/**'
    - 'vendor/**'

functions:
  # By default we create one "main" function
  main:
    handler: handler.handle
    timeout: 20
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
